language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mustafansrv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mustafansrv/react-test npm test -- --coverage

after_success:
  - docker build -t mustafansrv/multi-client ./client
  - docker build -t mustafansrv/multi-nginx ./nginx
  - docker build -t mustafansrv/multi-server ./server
  - docker build -t mustafansrv/multi-worker ./worker

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to Docker Hub
  - docker push mustafansrv/multi-client
  - docker push mustafansrv/multi-nginx
  - docker push mustafansrv/multi-server
  - docker push mustafansrv/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-Docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-867931605731"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

